language: cpp
script: PREFIX=/usr/local ./install.sh
compiler:
 - gcc
 - clang

before_install:
 - echo 'yes' | sudo add-apt-repository ppa:apokluda/boost1.53
 - sudo apt-get update -qq
 - sudo apt-get install -qq libtool python2.7-dev libboost1.53-all-dev libgsl0-dev libhdf5-serial-dev python-ply python-support doxygen

notifications:
  webhooks:
    urls:
      - http://dev.e-cell.org/ecell-bot/travis/notification
