language: cpp
script: sudo PREFIX=/usr/local PYTHONPATH=/usr/local/lib/python2.7/site-packages ./install.sh
compiler:
 - gcc
 - clang

before_install:
 - echo 'yes' | sudo add-apt-repository ppa:apokluda/boost1.53
 - sudo apt-get update -qq
# - sudo apt-get install -qq libtool python2.7-dev libboost1.53-all-dev libgsl0-dev libhdf5-serial-dev python-ply python-scipy python-support doxygen
# - git clone --depth=50 --branch=spatiocyte-compartment git://github.com/ecell/ecell3.git
# - sudo apt-get install -qq python-numpy python-gtk2 docbook-xml
# - (cd ecell3; ./autogen.sh && ./configure --with-boost-python-libname=boost_python-mt-py27 && make && sudo make install)
 - sudo apt-get install -qq libboost1.53-all-dev libgsl0-dev libhdf5-serial-dev
 - sudo apt-get install -qq python2.7-dev cython

notifications:
  webhooks:
    urls:
      - http://dev.e-cell.org/ecell-bot/travis/notification
