dist: trusty
sudo: false
language: cpp
matrix:
  include:
  - os: linux
    compiler: gcc
    language: python
    python: "2.7"
  - os: linux
    compiler: clang
    language: python
    python: "2.7"
  - os: linux
    compiler: gcc
    language: python
    python: "3.5"
  - os: linux
    compiler: clang
    language: python
    python: "3.5"
  - os: osx
    compiler: clang
    env: TRAVIS_PYTHON_VERSION="2.7"
  - os: osx
    compiler: clang
    env: TRAVIS_PYTHON_VERSION="3.5"

addons:
  apt:
    sources:
#    - sourceline: 'ppa:mc3man/trusty-media'
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - clang
    - libboost-dev
    - libgsl0-dev
    - libhdf5-serial-dev
    - python-dev
    - python3-dev
    - python3
    - python
    - wget
#    - ffmpeg

before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update; brew upgrade;
    brew install gsl ffmpeg;
    brew install homebrew/science/hdf5;
    if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then
      brew install python3;
      which python3;
      /usr/local/bin/python3 -V;
      brew install freetype;
    fi;
  fi

- which python
- python -V

- if [ "$TRAVIS_OS_NAME" == "linux" ]; then mkdir ~/local; wget https://bootstrap.pypa.io/get-pip.py; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then python get-pip.py; python -m pip install -U cython numpy matplotlib jupyter; fi; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then python get-pip.py; python -m pip install -U cython numpy matplotlib jupyter; fi; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then curl -O https://bootstrap.pypa.io/get-pip.py; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then /usr/local/bin/python get-pip.py; /usr/local/bin/python -m pip install -U cython numpy matplotlib jupyter; fi; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then /usr/local/bin/python3 get-pip.py; /usr/local/bin/python3 -m pip install -U cython numpy matplotlib jupyter; fi; fi

script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then bash -c 'cmake -DCMAKE_INSTALL_PREFIX=~/local . && make && make test && make install'; rm CMakeCache.txt; fi; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then bash -c 'cmake -DCMAKE_INSTALL_PREFIX=~/local . && make && make test && make install'; rm CMakeCache.txt; fi; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then sudo bash -c 'cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python . && make && make test && make install'; rm CMakeCache.txt; fi; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then sudo bash -c 'cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3 . && make && make test && make install'; rm CMakeCache.txt; fi; fi

- mkdir surge; cd ecell4-notebooks/Tutorials
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then LD_LIBRARY_PATH=~/local/lib:$LD_LIBRARY_PATH PYTHONPATH=~/local/lib/python2.7/site-packages:$PYTHON_PATH jupyter nbconvert --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=3600 --ExecutePreprocessor.kernel_name='python2' tutorial1.ipynb tutorial2.ipynb tutorial3.ipynb tutorial4.ipynb tutorial6.ipynb tutorial7.ipynb tutorial8.ipynb tutorial9.ipynb tutorial10.ipynb; fi; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then LD_LIBRARY_PATH=~/local/lib:$LD_LIBRARY_PATH PYTHONPATH=~/local/lib/python3.5/site-packages:$PYTHON_PATH jupyter nbconvert --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=3600 --ExecutePreprocessor.kernel_name='python3' tutorial1.ipynb tutorial2.ipynb tutorial3.ipynb tutorial4.ipynb tutorial6.ipynb tutorial7.ipynb tutorial8.ipynb tutorial9.ipynb tutorial10.ipynb; fi; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then /usr/local/bin/python -m jupyter nbconvert --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=3600 --ExecutePreprocessor.kernel_name='python2' tutorial1.ipynb tutorial2.ipynb tutorial3.ipynb tutorial4.ipynb tutorial6.ipynb tutorial7.ipynb tutorial8.ipynb tutorial9.ipynb tutorial10.ipynb; fi; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then /usr/local/bin/python3 -m jupyter nbconvert --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=3600 --ExecutePreprocessor.kernel_name='python3' tutorial1.ipynb tutorial2.ipynb tutorial3.ipynb tutorial4.ipynb tutorial6.ipynb tutorial7.ipynb tutorial8.ipynb tutorial9.ipynb tutorial10.ipynb; fi; fi
- mv *.html ../../surge/

deploy:
  provider: surge
  project: ./surge/
  domain: ecell4.surge.sh

notifications:
  webhooks:
    urls:
    - http://dev.e-cell.org/ecell-bot/travis/notification
  slack:
    secure: kCN8PCrinRfaDFKn93TMrYY5LberBt8GHDHOtSbR7B1Zmo9Pr/uHxxqoXlu1g9XYxgs2lud/AKo0gKMu8n+QHWeAXaOwe8GSccEqBdilXDVp4fzO96jT2R82RYljQ2wAR5ug1YIACRq06mtFn6U7GRZRnpRI4VsEUFLJPljZ+UM=
