language: cpp
script: PREFIX=/usr/local PYTHONPATH=/usr/local/lib/python2.7/site-packages ./install.sh
compiler:
 - gcc
 - clang

install: pip install -r requirements.txt

before_install:
 - echo 'yes' | add-apt-repository ppa:apokluda/boost1.53
 - apt-get update -qq
 - apt-get install -qq libboost1.53-all-dev libgsl0-dev libhdf5-serial-dev python-dev python-pip

notifications:
  webhooks:
    urls:
      - http://dev.e-cell.org/ecell-bot/travis/notification
