language: cpp
script: sudo PREFIX=/usr/local PYTHONPATH=/usr/local/lib/python2.7/site-packages:/usr/local/lib/python2.7/dist-packages ./install.sh
compiler:
 - gcc
 - clang

before_install:
 - echo 'yes' | sudo add-apt-repository ppa:apokluda/boost1.53
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost1.53-all-dev libgsl0-dev libhdf5-serial-dev
#  - sudo apt-get install -qq python2.7-dev cython
 - sudo apt-get install -qq python2.7-dev python-setuptools
 - sudo easy_install cython

notifications:
  webhooks:
    urls:
      - http://dev.e-cell.org/ecell-bot/travis/notification
