language: python
python:
  - "2.7"
  - "3.5"
language: cpp
os:
- linux
- osx
compiler:
- gcc
- clang
before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq cython libboost-all-dev libgsl0-dev libhdf5-serial-dev python-dev python-setuptools python-numpy python-scipy; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update -v; fi
script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo bash -c 'export PREFIX=/usr/local; export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH; ./install.sh py2'; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$CC" = "gcc" ]; then export CC=gcc-4.8; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$CC" = "gcc" ]; then export CXX=g++-4.8; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap ecell/ecell4; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ecell4 --HEAD; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH PYTHONPATH=/usr/local/lib/python2.7/site-packages python -c "from ecell4 import *"; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PYTHONPATH=/usr/local/Cellar/ecell4/HEAD/libexec/lib/python2.7/site-packages python -c "from ecell4 import *"; fi
notifications:
  webhooks:
    urls:
    - http://dev.e-cell.org/ecell-bot/travis/notification
  slack:
    secure: kCN8PCrinRfaDFKn93TMrYY5LberBt8GHDHOtSbR7B1Zmo9Pr/uHxxqoXlu1g9XYxgs2lud/AKo0gKMu8n+QHWeAXaOwe8GSccEqBdilXDVp4fzO96jT2R82RYljQ2wAR5ug1YIACRq06mtFn6U7GRZRnpRI4VsEUFLJPljZ+UM=
