os: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost
  BOOST_LIBRARYDIR: C:\Libraries\boost\stage\lib
  BUILD_EXAMPLES: OFF  # don't build examples to not exceed allowed build time (40 min)
  BUILD_TUTORIALS: OFF  # don't build tutorials to not exceed allowed build time (40 min)
  matrix:
    - BUILD_CORE_ONLY: ON
    - BUILD_CORE_ONLY: OFF
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"

init:
  - cmd: cmake --version

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "pip install cython"
  - ECHO "Where am I?:"
  - ps: "echo %cd%"
  - cd python
  - "python setup.py build_ext"

branches:
  only:
    - appveyor
