#os: Visual Studio 2015

environment:

  matrix:
    - GENERATOR: "Visual Studio 9 2008"
      ARCH: 32

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.9"
#    - PYTHON: "C:\\Python35"
#      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"

init:
  - cmd: cmake --version

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "curl -O https://bootstrap.pypa.io/get-pip.py"
  - "python get-pip.py
  - "pip install cython"
  - cd python
  - ECHO "ls boost:"
  - ps: "ls \"C:/Libraries/boost\""
  - "python setup.py build_ext -IC:/Libraries/boost"

build: false

branches:
  only:
    - appveyor
