#os: Visual Studio 2015

environment:
  PYTHON: "C:\\Python27"
  PYTHON_VERSION: "2.7.9"
  PYTHON_ARCH: "32"
  matrix:
  - GENERATOR: "Visual Studio 9 2008"
    ARCH: 32

init:
  - cmd: cmake --version

install:
  # install stdint
  - curl -O http://ftp.vector.co.jp/43/28/2114/stdint-20070624.zip
  - unzip stdint-20070624.zip
  # install gsl
  - curl -O http://r2d3.geldreich.net/downloads/gsl-1.13-windows-binaries.zip
  - unzip gsl-1.13-windows-binaries.zip
  # go into ecell4/python
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - "python get-pip.py"
  - "pip install cython"
  - cd python
  - ECHO "ls boost:"
  - ps: "ls \"C:/Libraries/boost\""
  - echo %CD%
  - "python setup.py build_ext -IC:/Libraries/boost;C:/projects/ecell4/stdint-20070624;C:/projects/ecell4/gsl/include"

build: false

branches:
  only:
    - appveyor
