#os: Visual Studio 2015

environment:
  PYTHON: "C:\\Python27"
  PYTHON_VERSION: "2.7.9"
  PYTHON_ARCH: "32"
  matrix:
  - GENERATOR: "Visual Studio 9 2008"
    ARCH: 32

init:
  - cmd: cmake --version

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - "python get-pip.py"
  - "pip install cython"
  - cd python
  - ECHO "ls boost:"
  - ps: "ls \"C:/Libraries/boost\""
  - curl -O curl -O http://ftp.vector.co.jp/43/28/2114/stdint-20070624.zip
  - unzip stdint-20070624.zip
  - move stdint-20070624 stdint
  - ECHO "pwd:"
  - ps: "chdir"
  - "python setup.py build_ext -IC:/Libraries/boost;C:/projects/ecell4/stdint"

build: false

branches:
  only:
    - appveyor
