#os: Visual Studio 2015

environment:
  global:
    HDF_DIR: "C:/Program Files (x86)/HDF_Group/HDF5/1.8.15/lib"
    BOOST_ROOT: C:\Libraries\boost
  PYTHON: "C:\\Python27"
  PYTHON_VERSION: "2.7.9"
  PYTHON_ARCH: "32"
  matrix:
  - GENERATOR: "Visual Studio 9 2008"
    ARCH: 32

init:
  - cmd: cmake --version

install:
  # install stdint
  - curl -O http://ftp.vector.co.jp/43/28/2114/stdint-20070624.zip
  - unzip stdint-20070624.zip
  # install gsl for build_ext
  - curl -O http://r2d3.geldreich.net/downloads/gsl-1.13-windows-binaries.zip
  - unzip gsl-1.13-windows-binaries.zip
  # install gsl for BesselTables
  # - cd ..
  # - curl -O http://www.icub.org/download/packages/windows/msvc10/gsl-1.14-bin-msvc10.zip
  # - unzip gsl-1.14-bin-msvc10.zip
  # - cd ecell4
  # cmake
#  - call "C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\vcvarsall.bat" x86
#  - cmake -G "NMake Makefiles" -DBOOST_REGEX_LIBRARIES=C:/Libraries/boost/libs -DBoost_INCLUDE_DIR=C:/Libraries/boost -DGSL_CBLAS_LIBRARIES=C:/projects/ecell4/gsl/lib -DGSL_LIBRARIES=C:/projects/ecell4/gsl/lib .
#  - nmake BesselTables
#  - cmake -G "Visual Studio 10" -D CMAKE_CXX_FLAGS_RELEASE="/MT" -D CMAKE_CXX_FLAGS_DEBUG="/MTd" -DBOOST_REGEX_LIBRARIES=C:/Libraries/boost/libs -DBoost_INCLUDE_DIR=C:/Libraries/boost -DGSL_INCLUDE_DIR=C:/projects/gsl-1.14/include -DGSL_CBLAS_LIBRARIES=C:/projects/gsl-1.14/lib -DGSL_LIBRARIES=C:/projects/gsl-1.14/lib .
  - cmake -G "Visual Studio 9 2008" -D CMAKE_CXX_FLAGS_RELEASE="/MT" -D CMAKE_CXX_FLAGS_DEBUG="/MTd" -DBOOST_REGEX_LIBRARIES=C:/Libraries/boost/libs -DBoost_INCLUDE_DIR=C:/Libraries/boost -DGSL_INCLUDE_DIR=C:/projects/ecell4/gsl/include -DGSL_CBLAS_LIBRARIES=C:/projects/ecell4/gsl/lib -DGSL_LIBRARIES=C:/projects/ecell4/gsl/lib .
  - cmake --build . --target BesselTables
  # install hdf5
  - mkdir hdf5lib
  - curl -O http://www.hdfgroup.org/ftp/HDF5/current/bin/windows/extra/hdf5-1.8.15-patch1-win32-vs2012-shared.zip
  - unzip hdf5-1.8.15-patch1-win32-vs2012-shared.zip
  - cd hdf5
  - msiexec /i HDF5-1.8.15-win32.msi /quiet /qn /norestart /log install.log
  - type install.log
  - xcopy "C:\Program Files (x86)\HDF_Group\HDF5\1.8.15\lib" c:\projects\ecell4\hdf5lib /I
  - cd ..
  # config.h
  - cd ecell4/core
  - move config.h.win32 config.h
  - cd ../egfrd
  - move config.h.win32 config.h
  - cd ../..
  # go into ecell4/python
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - "python get-pip.py"
  - "pip install cython"
  - cd python
  - ECHO "ls boost:"
  - ps: "ls \"C:/Libraries/boost\""
  - echo %CD%
  - "python setup.py build_ext -IC:/Libraries/boost;C:/projects/ecell4/stdint-20070624;C:/projects/ecell4/gsl/include -LC:/projects/ecell4/gsl/lib;C:/projects/ecell4/hdf5lib"

build: false

branches:
  only:
    - appveyor
