site_name: E-Cell4 documentation
pages:
  - ['index.md', 'Home']
  - ['about.md', 'About']
  - ['installation.md', 'Installation']
  - ['tutorials.md', 'Tutorials']
  - ['api/core.md', 'API', 'core']
